<a href="https://colab.research.google.com/github/vivekpenuli/linear-lasso-ridge-elastic/blob/master/ridge%2Classo_%2Celastic_net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_boston


In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
df=load_boston()

In [ ]:
df

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate p

In [ ]:
dataset = pd.DataFrame(df.data)
print(dataset.head())

        0     1     2    3      4   ...   8      9     10      11    12
0  0.00632  18.0  2.31  0.0  0.538  ...  1.0  296.0  15.3  396.90  4.98
1  0.02731   0.0  7.07  0.0  0.469  ...  2.0  242.0  17.8  396.90  9.14
2  0.02729   0.0  7.07  0.0  0.469  ...  2.0  242.0  17.8  392.83  4.03
3  0.03237   0.0  2.18  0.0  0.458  ...  3.0  222.0  18.7  394.63  2.94
4  0.06905   0.0  2.18  0.0  0.458  ...  3.0  222.0  18.7  396.90  5.33

[5 rows x 13 columns]


In [ ]:

dataset.columns=df.feature_names

In [ ]:
dataset.head()

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

In [ ]:
df.target.shape

(506,)

In [ ]:
dataset["Price"]=df.target


In [ ]:
dataset.head()


CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  Price
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2

[5 rows x 14 columns]

In [ ]:
X=dataset.iloc[:,:-1] 
y=dataset.iloc[:,-1] 

In [ ]:
X

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

#linear regression

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)


In [ ]:
score1=cross_val_score(LinearRegression(),X_train,y_train,cv=10,scoring='neg_mean_squared_error')
print(score1.mean())


-26.20371423172947


In [ ]:
mse_score=-score1
print(mse_score.mean())


26.20371423172947


In [ ]:
model1=LinearRegression()
model1.fit(X_train,y_train)
pre1=model1.predict(X_test)


In [ ]:
pre1

array([35.75549118, 24.88291659, 25.35144926, 29.13220336, 16.61613233,
       20.63738431, 13.25838455, 22.08506583, 21.61815219, 33.83890856,
       14.04369017, 17.68801924, 17.03756841, 35.72941459, 19.226767  ,
       17.66950841, 16.85037011, 32.51297136, 31.21460954, 11.67861569,
       29.26224732, 16.68060926, 27.71498772,  6.06975895, 25.50872929,
       19.66514699, 31.11518525, 17.99211778, 19.72250487, 24.0199608 ,
       24.72007169, 17.56895233, 22.81544837, 20.49739304, 21.26162608,
       19.1508945 , 17.18267882, 39.24874258, 15.74458747, 20.70996536,
        8.38652033, 24.42034818, 19.39948728, 21.56183219, 23.31235851,
       30.72733195, 24.82772545, 18.43408114, 32.50454193, 18.02085952,
       21.09084918, 23.55949123, 24.69990467, 20.18934441,  5.7806595 ,
       13.1759619 , 21.03733543, 13.00980195, 26.58500753, 32.17891452,
       20.93472105, 10.12092292, 21.74895634, 25.5307288 , 16.70064774,
       14.26409759, 14.05054673, 33.53795671, 42.41174214, 27.41

In [ ]:
y_test

306    33.4
320    23.8
70     24.2
369    50.0
345    17.5
       ... 
250    24.4
491    13.6
395    13.1
347    23.1
239    23.3
Name: Price, Length: 152, dtype: float64

In [ ]:
error1= (y_test - pre1) **2

In [ ]:
error1.mean()

21.17526143773597

In [95]:
pred_train_lr= model1.predict(X_train)
print((mean_squared_error(y_train,pred_train_lr)))
print(r2_score(y_train, pred_train_lr))
print(" ")

print("the mean squared error" , (mean_squared_error(y_test,pre1))) 
print("the square root error " ,np.sqrt(mean_squared_error(y_test,pre1))) 
print(r2_score(y_test, pre1))

22.9916713700408
0.7331388763313197
 
the mean squared error 21.175261437735966
the square root error  4.60165855292806
0.7360880928489422


# ridge regression

In [ ]:
C = [0.00036,0.00030,0.00039,0.00042,0.00045,0.0001,1,0.1]
avg_scores = {}  #it is a dictionary to store the kernal and c with its score
for cval in C:   #muiltiple for loop concep
  cv_scores =cross_val_score(Ridge(alpha=cval),X_train,y_train, cv=10,scoring='neg_mean_squared_error')
  avg_scores[str(cval)] = (cv_scores).mean()  

avg_scores

{'0.0001': -26.20370415822186,
 '0.0003': -26.20368408911991,
 '0.00036': -26.203678088631467,
 '0.00039': -26.203675091888567,
 '0.00042': -26.203672097479302,
 '0.00045': -26.203669105403215,
 '0.1': -26.204280691376045,
 '1': -26.42166063102253}

In [ ]:
model2=Ridge(alpha=0.00001)
model2.fit(X_train,y_train)
pre2=model2.predict(X_test)

In [ ]:
pre2[:20]

array([35.75548807, 24.88292035, 25.35144566, 29.13219784, 16.61613579,
       20.63738859, 13.25838556, 22.08508437, 21.61815431, 33.83890747,
       14.04368934, 17.68801385, 17.03757439, 35.72940797, 19.22676788,
       17.66951854, 16.85035475, 32.51296977, 31.21461884, 11.67862414])

In [ ]:
y_test[:20].values

array([33.4, 23.8, 24.2, 50. , 17.5, 20.1, 11.3, 22.2, 21.7, 32.4, 14. ,
       17.4, 23.2, 35.1, 17.1, 15.4, 19.1, 31.1, 35.4, 10.8])

In [ ]:
error2= ( y_test- pre2) **2

In [ ]:
error2

306      5.548324
320      1.172716
70       1.325827
369    435.465167
345      0.781216
          ...    
250      0.063754
491      0.009610
395     45.344598
347      4.438112
239     28.151017
Name: Price, Length: 152, dtype: float64

In [ ]:
error2.mean()

21.17525977834907

# lasso regression

In [ ]:
C1 = [1e-15,1e-100,1e-8,1e-3,1e-2,1,5,10,20,30,35,40,45,50,55,100]
lasso_avg_scores = {}  #it is a dictionary to store the kernal and c with its score
for cval1 in C1:   #muiltiple for loop concep
  lasso_cv_scores =cross_val_score(Lasso(alpha=cval1),X_train,y_train, cv=10,scoring='neg_mean_squared_error')
  lasso_avg_scores[str(cval1)] = (lasso_cv_scores).mean()  

lasso_avg_scores

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3577.6888870989924, tolerance: 2.706594301886793
  positive)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3533.6375478864416, tolerance: 2.7840495345911958
  positive)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3604.4245327470007, tolerance: 2.7086509685534597
  positive)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3736.61

{'0.001': -26.20363493683886,
 '0.01': -26.23103588728609,
 '1': -30.053361888272896,
 '10': -42.65740965000581,
 '100': -64.56323552942226,
 '1e-08': -26.203714226607286,
 '1e-100': -26.203714231729407,
 '1e-15': -26.203714231729407,
 '20': -51.169946439896805,
 '30': -61.57755033526253,
 '35': -62.308424341478506,
 '40': -62.94513953767986,
 '45': -63.454388493965055,
 '5': -39.770296607692245,
 '50': -63.6907745414439,
 '55': -63.732807555369185}

In [ ]:
model3=Lasso(alpha=0.001)
model3.fit(X_train,y_train)
pre3=model3.predict(X_test)

In [ ]:
pre3[:20]     


array([35.74960429, 24.89187307, 25.34408568, 29.10361203, 16.62546716,
       20.64849683, 13.26109165, 22.1251031 , 21.62350075, 33.81861853,
       14.04190022, 17.67870864, 17.04967576, 35.7163679 , 19.22953419,
       17.69008153, 16.81991433, 32.50946569, 31.23517812, 11.69600285])

In [ ]:
y_test[:20].values

array([33.4, 23.8, 24.2, 50. , 17.5, 20.1, 11.3, 22.2, 21.7, 32.4, 14. ,
       17.4, 23.2, 35.1, 17.1, 15.4, 19.1, 31.1, 35.4, 10.8])

In [ ]:
error3= (y_test - pre3) **2

In [ ]:
error3.mean()

21.19101722906483

# elastic net 

In [103]:
from sklearn.linear_model import ElasticNet
model4 = ElasticNet(alpha=0.1, l1_ratio=0.05)
model4.fit(X_train, y_train)

ElasticNet(alpha=0.1, copy_X=True, fit_intercept=True, l1_ratio=0.05,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [104]:
pre4=model4.predict(X_test)


In [105]:
pre4[:20]

array([35.01581909, 25.31872916, 24.6330295 , 28.6176786 , 17.26944541,
       21.28056381, 13.51343588, 24.25010368, 21.94768041, 33.46478917,
       13.05762748, 17.54077385, 17.49468088, 35.02651242, 18.81889313,
       18.28913569, 15.13850806, 32.18171545, 31.96664621, 12.41951116])

In [106]:
y_test[:20].values

array([33.4, 23.8, 24.2, 50. , 17.5, 20.1, 11.3, 22.2, 21.7, 32.4, 14. ,
       17.4, 23.2, 35.1, 17.1, 15.4, 19.1, 31.1, 35.4, 10.8])

In [107]:
error4= (y_test - pre4) **2

In [108]:
error3.mean()

21.19101722906483